### ISSUE TITLE
SwiftUI weak linking

### ISSUE THREAD

**Issue by pgawlowski** [ferranabello/Viperit#113]
Do you think it is possible to add availability for SwiftUI features in framework?
I accidentally run into crash because of that :(
Sth like 
`#if isAvailable()`
or version check might be helpful :) 

My failure was 

> dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
  Referenced from: /Users/piotrgawlowski/Library/Developer/CoreSimulator/Devices/818027B6-FE01-489E-937A-E7764561A2CE/data/Containers/Bundle/Application/D9182AB1-13FE-40CE-A395-45E6B06EA2F4/eForskrivning.app/Frameworks/Viperit.framework/Viperit
  Reason: image not found

**Comment by ferranabello** [comment]
Hi, what’s your app minimum deployment target? And also what dependency manager are you using? Carthage, Cocoapods, Swift Package Manager...

And the Xcode version too.

Thanks :)

**Comment by pgawlowski** [comment]
Cocoapods - 1.8.1
Xcode - 11.0
Deployment target - 11.0

BTW your podspec is not up-to-date with currently released version. 
s.version          = '1.4.0'
And release is 1.4.2 is it on purpose?

**Comment by cHicHillo** [comment]
I have the same problem: 

dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
  Referenced from: /Users/xxxxx/Library/Developer/CoreSimulator/Devices/CE491B26-0A12-4EF0-B484-527664AC5D67/data/Containers/Bundle/Application/66C02AA4-ACE0-4F79-9FFB-E1D47FAC0C27/xxxxx.app/Frameworks/Viperit.framework/Viperit
  Reason: image not found

**Comment by ferranabello** [comment]
Hi guys, thanks for the info. I'll try to publish a fix hopefully today 👍 

PR #115

**Comment by ferranabello** [comment]
Hey @pgawlowski and @cHicHillo,
I just pushed a new 1.4.3 release on Cocoapods.

I did some local testing with a simple Xcode11 project using the latest Cocoapods and running on iOS 12 simulator. Everything looks to be working now.

Let me know if it works for you. 
Cheers.

**Comment by ferranabello** [comment]
Fixed in #115
