### ISSUE TITLE
Provider injection

### ISSUE THREAD

**Issue by anton-manchenko** [ferranabello/Viperit#120]
I have a question: how do you plan to inject provider layer with module? ThanX

**Comment by ferranabello** [comment]
Hi @anton-manchenko,
injection really depends on you. But, one way of doing it is using custom router functions.

Let's say you have a MovieDetails module. Maybe you could have a function
`func show(from: UIViewController, data/provider/movie/whatever: Provider)` 

And use this function to build the module and inject your provider wherever you think it's necessary. I don't know if this answers your question.

Another way of doing injection would be to have custom build functions for your modules. To do that, just extend ViperitModule. Like I did to make a custom build function for SwiftUI injection:

```swift
extension ViperitModule {
    
    @available(iOS 13.0, *)
    func build<T: View, E: ObservableObject>(bundle: Bundle = Bundle.main, deviceType: UIUserInterfaceIdiom? = nil, setupUI: ((PresenterProtocol) -> (T, E))) -> Module {
        let components = allocateViperComponents(bundle: bundle)
        let set = setupUI(components.presenter)
        let viewUI = set.0
        
        let viewHost: UserInterfaceProtocol
        let envObject = set.1
        viewHost = HostingUserInterface(rootView: viewUI.environmentObject(envObject))

        return Module.build(view: viewHost, interactor: components.interactor,
                            presenter: components.presenter, router: components.router, displayData: components.displayData)
    }
}
```


Cheers

**Comment by anton-manchenko** [comment]
Ok, thanks, in generally I got answer on my question.
And i have another related question.
As i see you have Entity layer "Display data". Is it accessible only from View layer and this is data only for setup view?

**Comment by ferranabello** [comment]
The use of DisplayData is totally optional since some versions ago. It's supposed to be an entity accessible only from the view to get simple data like formatting, colors, texts etc.

But again, is totally optional. If you don't need it, just delete the class file

**Comment by anton-manchenko** [comment]
Ok, Thank you

**Comment by anton-manchenko** [comment]
I added store as optional item (same as Display data) into your solution, could we integrate it with your solution?

**Comment by ferranabello** [comment]
I don't think so, it's better to let everyone extend Viperit based on their specific requirements. Better to keep this framework simple and flexible 👍
