### ISSUE TITLE
Viperit: Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by ahmedraad** [ferranabello/Viperit#128]
There's an issue that happens only when downloading the app from testflight, otherwise running from Xcode works fine and I don't use storyboard or xib files it's only code

<img width="1274" alt="Screen Shot 2021-07-11 at 11 34 37 AM" src="https://user-images.githubusercontent.com/17860965/125188295-100af200-e23c-11eb-9a0a-c5630644a204.png">

And here's the implementation

```Swift
window = UIWindow(windowScene: scene)
let module = AppModules.splash.build()
module.router.show(inWindow: window, embedInNavController: false, setupData: nil, makeKeyAndVisible: true)
```

**Comment by ferranabello** [comment]
Hi @ahmedraad, how did you fix this crash?

Cheers

**Comment by ahmedraad** [comment]
> Hi @ahmedraad, how did you fix this crash?
> 
> Cheers

Hello @ferranabello 

I've seen a closed issue about optimization level fix so i did the same by making Swift Compiler - optimization level to No optimization

**Comment by ferranabello** [comment]
Cool! Thanks 👍
