### ISSUE TITLE
ViperIt unable to compile with Xcode 13

### ISSUE THREAD

**Issue by Speakus** [ferranabello/Viperit#129]
class HostingUserInterface - file UserInterface+SwiftUI.swift line 16
```Incorrect argument labels in call (have 'nibName:bundle:', expected 'coder:rootView:')```

**Comment by ferranabello** [comment]
Hi @Speakus ,
thanks for reaching out. Let's wait for the golden master release of Xcode 13. I'll keep an eye on it.

Cheers.

**Comment by ferranabello** [comment]
I was able to reproduce it with Xcode 13 RC version. Working on a solution, thanks 👍

**Comment by ferranabello** [comment]
Fixed on #131

**Comment by ferranabello** [comment]
Published new version v1.5.0 with the fix 👍
