### ISSUE TITLE
Apply SwiftLint

### ISSUE THREAD

**Issue by buguibu** [ferranabello/Viperit#31]
First of all let me congratulate you, this is the best approach to VIPER I have seen and it's close to mine but using a bigger knowledge on Swift.

But it doesn't compile against https://github.com/realm/SwiftLint , i can exclude your Pod from the listing process but as i rather to understand your source would be cooler if it were linted.

Even excluding Pods from the linting, the modules generated by the template includes at least two lint errors that could be easily fixed:

- the forced casts on VIPER componentes getters `var presenter: LoginPresenter { return _presenter as! LoginPresenter }`
- the use of underscore on the same VIPER componentes, on my VIPER architecture I called them proxyPresenter, proxyRouter...

**Comment by buguibu** [comment]
I have fix this on my fork you can take a look at it https://github.com/buguibu/Viperit , this is the first time I do source coda collaborations on a public repo so I really don't know how this work, so forgive me if do any nosense.

**Comment by ferranabello** [comment]
Hi @buguibu, thanks a lot for your comments!

I'll have a look at what you said. You can do a pull request with what you think it's best for code styling, and then we can discuss about those changes. If the changes are for the templates, you can fork this repo: https://github.com/ferranabello/ViperitTemplates

It's a good idea to have at least the templates linter compliant, so this framework is as plug-and-play as possible.

Again, thanks for helping out!

Cheers!

**Comment by buguibu** [comment]
I also have forked the templates repo and linted in a separate branch.
