### ISSUE TITLE
Swift 3 syntax error

### ISSUE THREAD

**Issue by buguibu** [ferranabello/Viperit#32]
Starting a project from scratch Xcode and added my fork of this repo as a development pod Xcode complains about Swift 3 syntax, I perform the automatic conversion and raises about 94 errors, what I'm doing wrong?

**Comment by ferranabello** [comment]
I cloned the Viperit repo and everything is building fine.

You should just clone the repo and and open the Xcode project file. You don't need to create a development pod. You'll see that the project has 3 targets. The framework itself, the tests and the example app.
