### ISSUE TITLE
Get-only viper components do not allow protocol properties

### ISSUE THREAD

**Issue by buguibu** [ferranabello/Viperit#34]
## Scenario
Trying to mock a splash page that will wait for resources to be loaded before push to home I have this code:

```swift
// MARK: - Public Interface Protocol
protocol SplashViewInterface {
    var isStuffReady: Bool { get set }
}
//....
extension SplashPresenter: SplashPresenterInterface {
    func stuffReady() {
        view?.isStuffReady = true //Error: Cannot assign to property: 'view' is a get-only property
    }
}
```
To solve this I have 2 options:
### Auto generated setters for Viper components
```swift
// MARK: - VIPER COMPONENTS API (Auto-generated code)
private extension SplashPresenter {
    var view: SplashViewInterface? {
        get {
            return proxyView as? SplashViewInterface
        }
        set {
            proxyView = newValue as? UserInterface
        }
    }
```

### Avoid properties on modules interfaces
Instead use a implicit computed property 
```swift
protocol SplashViewInterface {
    var isStuffReady: Bool { get set }
    func setStuffLoaded(isLoaded: Bool)
}
//....
/ MARK: Splash View
final class SplashView: UserInterface {
    var isStuffReady = false
}

// MARK: - Public interface
extension SplashView: SplashViewInterface {
    func setStuffLoaded(isLoaded: Bool) {
        isStuffReady = isLoaded
    }
}
```
## Question
Does it make sense to have properties on protocols?

**Comment by ferranabello** [comment]
Hi @buguibu, I think that this kind of protocols in Viper should look like an API, so I think that the neat solution would be to define a method in the api to update certain things of the view for example. Just like you did.

So in this case, something like:
```swift
protocol SplashViewInterface {
    func setStuffLoaded(isLoaded: Bool)
}
```

You don't need the var anymore. Just think of the view interface as the view api. It's much more clear to call a function than updating a variable.

I would suggest that, for this kind of api, is better to use get-only variables. So, just use variables to get data from a certain component.

Cheers!

**Comment by buguibu** [comment]
Make sense, coming from objective-c where I prefer to use getters and setters it's right for me.
