### ISSUE TITLE
Suggestion: Event about Module Builded

### ISSUE THREAD

**Issue by EvsenevDev** [ferranabello/Viperit#41]
What do you think if we add event for each layer about Module Builded
For example:
Each layer implement protocol ViperLayer
with **func onModuleBuilded** event
we call this after all layers is connected in **build**

this helps us with initalization for each layer when dependecies are connceted
For example:
in this event we can call presenter from interactor after init

**P.S.** Now if we override standard **init** we can't call presenter from interactor

**Comment by ferranabello** [comment]
Hi @EvsenevDev, I don't think that's a good idea, at least for viper. The only entry point for a module should be always its router. Any further action should be triggered by the router to the presenter, then from the presenter to the view/interactor, and so on.

But we could add more functions for the developer to override to simplify things. For now, we have these methods only:

```swift
    func setupView(data: Any)
    func viewHasLoaded()
    func viewIsAboutToAppear()
    func viewHasAppeared()
    func viewIsAboutToDisappear()
    func viewHasDisappeared()
```

We can sure think about what methods we'd need to make our life easier :-)
