### ISSUE TITLE
Setup data on Interactor.

### ISSUE THREAD

**Issue by buguibu** [ferranabello/Viperit#43]
As i understand VIPER, the interaction is the only one data provider to the presenter, so the setup data should be injected onto it and retrieved by the presenter when showing the module.

Along with this and for not create another issue, I didn't´t get the key concept of DisplayData entity and on my work I'm omitting it.

**Comment by ferranabello** [comment]
Hi @buguibu, I'm not sure If I understood the first question. SetupView() is just a convenience method that I added in the presenter so you don't have write it if you don't want to. But this kind of entry point should be with really simple data. Thins like setupView(data: "James") or whatever. Then the presenter will implement there the logic to call the interactor and fetch the data that it needs.

Answer to the 2nd question:
DisplayData is just for static or really dummy data. Think for example in localized strings, colors, heights, widths, methods for calculating frames, things like that. It's very useful to keep your view really clean and simple. But, of course, we can think on  having a module without this dependency.

**Comment by chrain** [comment]
@ferranabello  thank for this issure, i know `DisplayData` in `Viperit` what can do.
