### ISSUE TITLE
App crashes run time 

### ISSUE THREAD

**Issue by mubasherkhan** [ferranabello/Viperit#58]
I have build a project according to viperit instructions then app crashes on the start .That can be seen in screen shot .Here is my AppDelegate source 
` import UIKit
import Viperit
enum AppModules: String, ViperitModule {
    case myFirstModule
}
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        window = UIWindow(frame: UIScreen.main.bounds)
        let module = AppModules.myFirstModule.build()
        module.router.show(inWindow: window)
        return true
    }
`
<img width="1440" alt="screen shot 2017-09-28 at 11 14 56 am" src="https://user-images.githubusercontent.com/11816744/30951872-a352f75a-a43e-11e7-8524-e78a256d57d3.png">

**Comment by trukhachev** [comment]
Can't find the class. Try to rename.

modules/myFirstModule/**M**yFirstModuleInteractor
modules/myFirstModule/**M**yFirstModulePresenter
...

class myFirstModuleInteractor -> class **M**yFirstModuleInteractor

**Comment by mubasherkhan** [comment]
Thanks renaming the class solved my problem

**Comment by ferranabello** [comment]
Thanks for helping out @trukhachev!. I'll add more information about the naming convention in the docs @mubasherkhan 👍
