### ISSUE TITLE
How do I create UITabBarController with Viperit!

### ISSUE THREAD

**Issue by tharhtet** [ferranabello/Viperit#59]
Could I get the example with UITabBarController with Viperit without NavigationController? Thanks a lot.

**Comment by ferranabello** [comment]
Hi @tharhtet, to use a UITabBarController with Viperit I suggest you to subclass UITabBarController and do something like this:

```swift
import UIKit

final class AppTabBar: UITabBarController {
    func setup() {
        var modules: [AppModules] = [
            .module1,
            .module2,
            .module3,
            .module4
        ]
        
        viewControllers = modules.map({ mod -> UIViewController in
            let module = mod.build()
            let view = module.router.embedInNavigationController()
            
            // In case you don't need a navigationController
            // let view = module.router._view
            
            return view
        })
    }
}
```

This is a very simple solution. Of course you could add more configuration to this and inject the dependencies in the setup function or configuration classes or stuff like that.

Anyway, this will get you what you want.

Cheers man!

**Comment by tharhtet** [comment]
Thanks for your help. :) :)
