### ISSUE TITLE
Alamofire API Request

### ISSUE THREAD

**Issue by tharhtet** [ferranabello/Viperit#61]
Could I get the sample format with Alamofire in Viperit like [iOS-Viper-Architecture](https://github.com/MindorksOpenSource/iOS-Viper-Architecture). And How do I create the storyboard for iPad and iPhone within one module because iPad and iPhone was difference Design? Thanks a lot.

**Comment by tharhtet** [comment]
And May I know how to pass the data from firstview to second view, Thanks?

**Comment by ferranabello** [comment]
HI @tharhtet,

- About having specific tablet design:
To use different views for iPhone and iPad you just have to create your module selecting the option "Dedicated tablet view". This will get you separate views 👍.

- About how to pass data across modules:
I encourage you to pass simple data using your module's router. So, imagine you have a module A that has a list of elements and a module B that will show one specific element.

One possible solution would be to have a unique identifier for each element of the list. Once you tap on an element of the list, the view will ask the presenter to show that specific element with that specific id. Sequentially, the presenter will tell its router to show the new screen using that identifier.

Viperit offers you a lot of flexibility. You could implement a lot of different solutions. If you want to use some of the built-in convenience methods in the routers:

```swift
    func show(inWindow window: UIWindow?, embedInNavController: Bool, setupData: Any?, makeKeyAndVisible: Bool)
    func show(from: UIViewController, embedInNavController: Bool, setupData: Any?)
    func show(from containerView: UIViewController, insideView targetView: UIView, setupData: Any?)
```

Notice that you could use the setupData parameter to pass anything you want. Maybe that could be useful for you. But, again, try whatever suits you best.

Cheers.

**Comment by tharhtet** [comment]
Thanks a lot.
