### ISSUE TITLE
ViewController presentation styles

### ISSUE THREAD

**Issue by pgawlowski** [ferranabello/Viperit#67]
Hi,

First of all - good job. It is sth I was looking for recently.

Few questions. 
Is it possible to request for implementation of > UIModalPresentationStyle 

What is your suggestion about SplitViewControllers in that case? Skip the router part?

**Comment by ferranabello** [comment]
Hi @pgawlowski,
sure, I'll add your request to the list :)

Talking about SplitViewControllers, I woud always use the Router and not skip it. But you should implement it creating a container module.

Let's say we are developing a messaging app using Viperit. And, for the tablet version, we want to show the inbox on the left side of the screen and the selected conversation on the right side.

This is a possible solution. Three modules:
- MessageCenter
- Inbox
- Conversation

MessageCenter will be the container module. It will handle the logic to instantiate and show its child modules (inbox and conversation).

This is an example of what we should write in the MessageCenterRouter:
```swift
// MARK: - MessageCenterRouter API
extension MessageCenterRouter: MessageCenterRouterApi {
    func showInbox(intoListContainer: UIView, withConversationContainer: UIView) {
        let inboxModule = AppModules.inbox.build()
        inboxModule.router.show(from: _view, insideView: intoListContainer, setupData: nil)
        
        let conversationModule = AppModules.conversation.build()
        conversationModule.router.show(from: _view, insideView: withConversationContainer, setupData: nil)
    }
}
```

This is just an example. Let me know what you think.

Cheers!

**Comment by pgawlowski** [comment]
@ferranabello after a while I came to this kind of concept as well. 
Currently I have no time to verify it in practice (sadly my current project forced me to use other architectural pattern) however for sure I will use Viperit with one of my private projects.

Thank you very much for adding my request about modals. Maybe I will find some time to contribute to your work and prepare sth on my own :) 

Cheers!
