### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by mapo80** [ferranabello/Viperit#70]
Hi,

interesting framework and library, I've two questions:

- If I need a custom UIViewController what do I have to do? I've to create a custom UserInterface that inherits from my custom UIViewController? I've seen that UserInterface inherits from UIViewController. Here (https://github.com/ferranabello/Viperit/issues/69) you say that we have to thins Eureka as a subview but it complicates things. 
If we want to simplify could we create a custom UserInterface. Could you give us an example?

- In you framework there's DisplayData. How should it be used?

Thanks

**Comment by astrokin** [comment]
@mapo80 the idea for DisplayData is to get all any kind of strings/images etc UI related data from it. It allow you to easily have different view controllers for iPad and iPhone but take the same UI data.

**Comment by elprl** [comment]
Is that not the goal of the Presenter to provide that presentation logic?
``` 
if .iPad {
    view.updateLabel(myPadString)
} else {
    view.updateLabel(myPhoneString)
}
```

I think you run the risk of having DisplayData class being confused with some kind of ViewModel class, which should be left to the developer using the framework to decide whether to use or not. I'm not sure this should be part of the core generated code. Just my humble opinion.

**Comment by ferranabello** [comment]
Closed due to inactivity
