### ISSUE TITLE
Example update

### ISSUE THREAD

**Issue by pgawlowski** [ferranabello/Viperit#72]
@ferranabello 
Hey,

Any chance for updated example? 

I wonder how you imagine for example ApiProtocol part.

Let's assume that we've got LoggedOut module. 
Let's click button login 

Protocol supposed to look like

```
protocol LoggedOutRouterApi: RouterProtocol {
    func showRegisterModule()
}
//MARK: - LoggedOutPresenter API
protocol LoggedOutPresenterApi: PresenterProtocol {
    func showRegisterModule()
}

```
declaring those methods twice in protocol and 

```
final class LoggedOutView: UserInterface {
    @IBAction func presentRegister() {
        presenter.showRegisterModule()
    }
}
```

as action handling for view?

There are lot more things I am not sure how to use with Viperit :) It would be nice to have this example updated.

**Comment by ferranabello** [comment]
Hi @pgawlowski ,
it's definitely in my ToDo list updating the docs and the example.

Thanks for the feedback 👍
