### ISSUE TITLE
RxBindings between presenter and view

### ISSUE THREAD

**Issue by pgawlowski** [ferranabello/Viperit#74]
@ferranabello 
What do you think about exposing 

DisplayData to presenter to use it as exchange object for RxBindings between View and Presenter?

If it's not an option what is your suggestion to handle this kind of bindings?

**Comment by ferranabello** [comment]
Hi @pgawlowski ,
in my projects I use DisplayData as a class for data like style, strings, colors and really basic calculations. To do bindings between the presenter and the view I would expose a view model object from the presenter to the view. This is what I would write in the view:

```swift
//Bind fields to view model
let vm = presenter.viewModel
(nameField.rx.text<->vm.name).disposed(by: rxBag)
(lastNameField.rx.text<->vm.lastName).disposed(by: rxBag)
(phoneField.rx.text<->vm.phone).disposed(by: rxBag)
(emailField.rx.text<->vm.email).disposed(by: rxBag)
(companyField.rx.text<->vm.company).disposed(by: rxBag)
```

But again, there is no right or wrong here, do whatever you feel is better.

Cheers!
