### ISSUE TITLE
Compile error in pod on Xcode 10 beta 5

### ISSUE THREAD

**Issue by elprl** [ferranabello/Viperit#76]
In `Router` class:

```    
open func show(from: UIViewController, embedInNavController: Bool = false, setupData: Any? = nil) {
        process(setupData: setupData)
        let view = embedInNavController ? embedInNavigationController() : _view
        from.show(view, sender: nil)
    }
```
Line 38 ` from.show(view, sender: nil)`has error: Value of optional type 'UIViewController?' must be unwrapped to a value of type 'UIViewController'

Anyone else seeing this?

**Comment by elprl** [comment]
Looks like it might be an Xcode beta issue. It doesn't seem to like the ternary conditional operator and nil coalescing operator combo. I fixed with:
`let view: UIViewController = embedInNavController ? embedInNavigationController() : _view`

**Comment by ferranabello** [comment]
Hi @elprl ,
thanks for the info.

I'll take a look into it when the Xcode 10 golden master version gets released.

Cheers!
