### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by DiegoCaridei** [ferranabello/Viperit#77]
ViperIt template folder is empty

**Comment by allanalves** [comment]
@DiegoCaridei open it through Github and you will see a link to another repo:
https://github.com/ferranabello/ViperitTemplates

**Comment by DiegoCaridei** [comment]
@allanalves Thank you

**Comment by ferranabello** [comment]
Hi @DiegoCaridei @allanalves ,
you could also use this:

`git clone --recurse-submodules git://github.com/ferranabello/Viperit.git`

This will clone the repo and all its submodules.

Cheers 👍

**Comment by DiegoCaridei** [comment]
@ferranabello  thanks 👍
