### ISSUE TITLE
Use module with view variants

### ISSUE THREAD

**Issue by pgawlowski** [ferranabello/Viperit#78]
Is it possible to use same module, but build it with different .storyboard?
How to achieve this?

**Comment by ferranabello** [comment]
Hi @pgawlowski ,
sure you can.

You just have to override the default implementation of the "viewName" property in your modules enum.

For example:

```swift
enum AppModules: String, ViperitModule {
    case home
    case second
    
    var viewName: String {
        switch self {
        case .home:
            if someSpecialThingHappens {
                return "homeSpecial"
            } else {
                return "home"
            }
        default:
            return rawValue
        }
    }
}
```

Just remember that you will need to put "*Module*View" (where *Module* is your module name) as the ViewController identifier (Storyboard ID in interface builder) in each of your storyboard files.

Cheers.
