### ISSUE TITLE
Support UITableViewController

### ISSUE THREAD

**Issue by allanalves** [ferranabello/Viperit#79]
Any plans for supporting the lib to use UITableViewControllers instead of only using UIViewController (UserInterface class implementation)?

**Comment by ferranabello** [comment]
Hi @allanalves ,
I have no plans to add support for UITableViewControllers at the moment. The idea was to use old plain UIViewControllers.

Anyway it would be cool to support it, but I still have some design doubts about how to be able to support any UIViewController subclass.

Thanks!

**Comment by allanalves** [comment]
Thanks, @ferranabello. It would be nice if it supports UITabBarController too! 

Congrats for the project.

**Comment by ferranabello** [comment]
Hi @allanalves,
this PR #100 should add support to any custom or third party UIViewController (including UITableViewController's). The only thing you need to do to make them work is implement the UserInterfaceProtocol by your own.

This is implemented in the **feature/viewcontroller-agnostic-views** branch
