### ISSUE TITLE
HomeTests.testShowInfo1 test case doesn't compile

### ISSUE THREAD

**Issue by AlexanderBollbach** [ferranabello/Viperit#8]
compiler says 'loadContent' is inaccessible due to 'fileprivate' protection level

**Comment by kszuba** [comment]
You need to remove "private" from "private extension HomePresenter". This will resolve problem

**Comment by ferranabello** [comment]
Hi @AlexanderBollbach, @kszuba is right. I've updated the code.

Thanks!
