### ISSUE TITLE
Modally presentation styles

### ISSUE THREAD

**Issue by sergiusKurganov** [ferranabello/Viperit#88]
Hello!

I use your library and I like it. 
I need to use a special **modal presentation style** but it's difficult. I want to propose adding this functionality to your cool library ;)

**Comment by sergiusKurganov** [comment]
> Hello!
> 
> I use your library and I like it.
> I need to use a special **modal presentation style** but it's difficult. I want to propose adding this functionality to your cool library ;)

**Comment by sergiusKurganov** [comment]
> Hello!
> 
> I use your library and I like it.
> I need to use a special **modal presentation style** but it's difficult. I want to propose adding this functionality to your cool library ;)

**Comment by sergiusKurganov** [comment]
> Hello!
> 
> I use your library and I like it.
> I need to use a special **modal presentation style** but it's difficult. I want to propose adding this functionality to your cool library ;)

My pull-request :)
https://github.com/ferranabello/Viperit/pull/89#issue-237369984

**Comment by ferranabello** [comment]
Hi @sergiusKurganov,
thanks a lot!

This will make our life easier for simple modules :) 
I added a comment to the PR #89.

Created the PR #90 instead.

Cheers.
