### ISSUE TITLE
How to test modules?

### ISSUE THREAD

**Issue by ufeub** [ferranabello/Viperit#92]
Hello. Thanks for very useful project.
And how we can test module (presenter, interactor)? We need mock some layers (view for example) but we can't.

**Comment by ferranabello** [comment]
Hi @ufeub,
you can check out the tests in the example app to see how they work.

This is an example of injecting a mock view:

```swift
var mod = AppModules.home.build()
        view = HomeMockView()
        view.expectation = expectation(description: "Test expectation description")
        mod.injectMock(view: view)
        ....
```

Let me know if it works for you 👍

**Comment by ferranabello** [comment]
Hi @ufeub,
I'll close this issue since you didn't give any feedback.

Feel free to reopen it if necessary.

Cheers.
