### ISSUE TITLE
Using MDCTabBarViewController with Viperit?

### ISSUE THREAD

**Issue by abhishekInvesto2o** [ferranabello/Viperit#98]
How to use any other custom viewcontrollers like MDCTabBarViewController or MXSegmentedPagerController with Viperit?

**Comment by ferranabello** [comment]
If you have third party UIViewController subclasses you need them to be compliant with the **UserInterfaceProtocol**

```swift
class ThirdPartyViewController: UIViewController { ... }
class MyModuleView: ThirdPartyViewController, UserInterfaceProtocol { ... }
```

**Comment by abhishekInvesto2o** [comment]
<img width="1007" alt="screenshot 2019-02-18 at 2 52 37 pm" src="https://user-images.githubusercontent.com/46316117/52940567-e4e28800-338c-11e9-9ccf-61c15830a9bc.png">

Got this error while i used this code

```
final class UserDetailsView: MDCTabBarViewController, UserInterfaceProtocol {
    var _presenter: Presenter!
    var _displayData: DisplayData!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        _presenter.viewHasLoaded()
         ...
        }
}
```

**Comment by ferranabello** [comment]
In your storyboard file, in interface builder right pane, set **UserDetailsView** as the **Storyboard ID** of your view controller

**Comment by abhishekInvesto2o** [comment]
UserDetailsView is already set.
<img width="336" alt="screenshot 2019-02-18 at 3 08 58 pm" src="https://user-images.githubusercontent.com/46316117/52941656-56233a80-338f-11e9-964d-c4adff553b7f.png">

Error:-
Could not cast value of type 'xxx.UserDetailsView' (0x100b88fc8) to 'Viperit.UserInterface' (0x101959788).

**Comment by ferranabello** [comment]
Ok, the only way for now then is to fork this third party view controller and make it a subclass of UserInterface instead of UIViewController 👍 

```swift
class ThirdPartyFrameworkView: UserInterface, .... {}
```

**Comment by abhishekInvesto2o** [comment]
Is there no other way or easy fix without forking. I mean changing the code in this library? So that while returning viewcontroller from storyboard it checks whether UserInterfaceProtocol has been impletmented or not?

**Comment by ferranabello** [comment]
It's not a quick fix. If you really need this library to be integrated with Viperit I suggest you to do that for now. This third-party ViewControllers are modules itself (not the original idea of Viperit of using plain old view controllers and compose other components inside). I'm thinking about a way of interacting with third party frameworks.

I'll let you know 👍 

PS: It's not a quick fix because I don't want to make breaking changes if possible

**Comment by abhishekInvesto2o** [comment]
Great. But in the meantime I would suggest future readers to use the thirdparty library to add as a child controller of the UserInterface class view. :)

**Comment by ferranabello** [comment]
Hi @abhishekInvesto2o,
please check out the branch **feature/viewcontroller-agnostic-views**. I think I came up with a clean solution :)

Let me know what you think 👍

**Comment by abhishekInvesto2o** [comment]
It looks great. :). Thanks for the implementing the much needed feature.
